name:                hspec-golden
version:             0.2.2.0
github:              "stackbuilders/hspec-golden"
license:             MIT
author:              "Stack Builders"
maintainer:          "Cristhian Motoche <cmotoche@stackbuilders.com>"
copyright:           "2019-Present Stack Builders Inc"
synopsis:            "Golden tests for hspec"
category:            Testing
tested-with:         GHC==8.8, GHC==8.10, GHC==9.0

extra-source-files:
- README.md
- ChangeLog.md

description: |
  .
  Golden tests store the expected output in a separated file. Each time a golden test
  is executed the output of the subject under test (SUT) is compared with the
  expected output. If the output of the SUT changes then the test will fail until
  the expected output is updated.
  .
  @hspec-golden@ allows you to write golden tests using the popular @hspec@.
  .
  > describe "myFunc" $
  >   it "generates the right output with the right params" $
  >      let output = show $ myFunc params
  >        in defaultGolden "myFunc" output
  .
  Please see the <https://github.com/stackbuilders/hspec-golden#readme README on GitHub>
  for more information.

dependencies:
- base >= 4.6 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Test.Hspec.Golden
  dependencies:
  - directory >= 1.3.6 && < 1.4
  - filepath >=1.0 && <2.0
  - hspec-core >= 2.10 && < 3.0

executables:
  hgold:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec-golden
    - directory >= 1.2.5.0
    - optparse-applicative >= 0.18.1 && < 0.19
    - ansi-terminal >= 1.0 && < 2.0

tests:
  hspec-golden-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - silently
    - hspec
    - hspec-golden
    - hspec-core
    build-tools:
      - hspec-discover:hspec-discover >= 2.0  && < 3.0
