name:                hspec-golden
version:             0.1.0.1
github:              "stackbuilders/hspec-golden"
license:             MIT
author:              "Stack Builders"
maintainer:          "cmotoche@stackbuilders.com"
copyright:           "2019-2020 Stack Builders Inc"
synopsis:            "Golden tests for hspec"
category:            Testing

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/stackbuilders/hspec-golden#README>

dependencies:
- base >= 4.6 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Test.Hspec.Golden
  dependencies:
  - directory
  - hspec-core

executables:
  hgold:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec-golden
    - directory >= 1.2.5.0
    - optparse-applicative

tests:
  hspec-golden-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - silently
    - hspec
    - hspec-golden
    - hspec-core
