name:                fizzbuzz
version:             0.1.0.0
github:              "githubuser/fizzbuzz"
license:             BSD3
author:              "Jorge Guerra"
maintainer:          "cmotoche@stackbuilders.com"
copyright:           "2019 StackBuilders"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/fizzbuzz#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src


tests:
  fizzbuzz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fizzbuzz
    - hspec
    - hspec-golden
