name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.0"
          cabal-version: "3.8"

      - name: Build source distribution
        run: cabal sdist

      - name: Upload to Hackage
        run: cabal upload --publish --username=stackbuilders --password=${{ secrets.HACKAGE_TOKEN }} dist-newstyle/sdist/*.tar.gz
